name: Create Vhost

on: [push]

jobs:
  create-vhost-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test bash script
        run: echo "This is test bash script"