name: Create Vhost

on: [push]

jobs:
  create-vhost-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: |
          sudo apt-get -y install sshpass
      - name: Add known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 3.142.169.168 > ~/.ssh/known_hosts
      - name: Create Virtual Host
        run: |
          sshpass -p ubuntu ssh ubuntu@3.142.169.168 <<EOF
            cd scripts
            rm *
            wget https://raw.githubusercontent.com/sghsgm99/dns-vhost/main/vhost.sh
            chmod +x vhost.sh
            sudo ./vhost.sh
          EOF
      
