name: Create Vhost

on:
  workflow_dispatch:
    inputs:
      host:
        description: 'Domain Host'
        required: true
      servn:
        description: 'Server Name'
        required: true
      cname:
        description: 'CName'
        required: true
      username:
        description: 'Username'
        required: true  
      password:
        description: 'Password'
        required: true
jobs:
  create-vhost-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: |
          sudo apt-get -y install sshpass
      - name: Add known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ github.event.inputs.host }} > ~/.ssh/known_hosts
      - name: Create Virtual Host
        run: |
          sshpass -p ${{ github.event.inputs.password }} ssh ${{ github.event.inputs.username }}@${{ github.event.inputs.host }} <<EOF
            wget -O vhost.sh https://raw.githubusercontent.com/sghsgm99/dns-vhost/main/vhost.sh
            chmod +x vhost.sh
            sudo ./vhost.sh ${{ github.event.inputs.servn }} ${{ github.event.inputs.cname }}
          EOF
      
