name: Create Vhost

on:
  workflow_dispatch:
    inputs:
      host:
        description: 'Client host'
        required: true
      servn:
        description: 'servn'
        required: true

jobs:
  create-vhost-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: |
          sudo apt-get -y install sshpass
      - name: Add known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ github.event.inputs.host }} > ~/.ssh/known_hosts
      - name: Create Virtual Host
        with:
          servn: ${{ github.event.inputs.servn }}
        run: |
          sshpass -p ubuntu ssh ubuntu@${{ github.event.inputs.host }} <<EOF
            cd scripts
            rm *
            wget https://raw.githubusercontent.com/sghsgm99/dns-vhost/main/vhost.sh
            chmod +x vhost.sh
            sudo ./vhost.sh
          EOF
      
