name: Create Vhost

on: [push]

jobs:
  create-vhost-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: |
          sudo apt-get -y install sshpass
      - name: Add known hosts
        run: |
          ssh ubuntu@3.142.169.168
          ubuntu
      
