name: Create Vhost

on: [push]

jobs:
  create-vhost-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test bash script
        run: echo "This is test bash script"
      - name: Install packages
        run: |
          ls
          ls ${{ github.workspace }}
      - name: Add known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ github.event.inputs.host }} > ~/.ssh/known_hosts
